uktrade/redbox

redbox-core/redbox/loader/loaders.py, redbox-core/redbox/models/settings.py
The previous version use GPT to extract metadata from uploaded files. Need to change it to use Claude.
- Update metadata llm to Claude
- Update the chain to use structured output
=> Update metadata llm to Claude

.gitignore, django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/feedback-buttons.js
Implemented new metrics with labels agreed by UR research.
Changed feedback buttons Thumbs up and Down for usefullnes, and new feedback chips. 
Test functionality and review collecting data
=> Label metrics

django_app/redbox_app/settings.py
Add in required CSP config for Google Analytics to work
=> chg: will add CSP config for google analytics

django_app/redbox_app/templates/homepage.html
We have a hardcoded security level as legacy i.ai fork
Make it not hardcoded
Check it works
=> fix: hardcoded security should not be there

ai-tests/tests/test_ai.py, redbox-core/redbox/chains/runnables.py
We need to be able to pull correct model name that is used to produce results at runtime.
- modify the code to grab model name from llm
- fix ai_test to work with open search query structure
- fix saving ai test outputs issue due to file closed before it finishes writing
=> Bugfix/model name and test_ai

ai-tests/tests/test_ai.py
test_ai.py is not working.
- change the query to open search to match the open search syntax.
=> Fix opensearch query in ai test

django_app/redbox_app/redbox_core/serializers.py
We would like a table in data workspace that reflects all user details we have so far without exposing PII
Adds all the missing fields for the serializer
Check I didnt miss anything
=> feat: complete serializer for user details

django_app/redbox_app/templates/macros/iai-top-nav.html
We want to see a feedback link in header
Adding a feedback link in header
Check you're happy with the approach
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-461
=> feat: feedback in header link

django_app/redbox_app/redbox_core/serializers.py
To build our second pipeline we need to make these changes to the serializer  
Update fields to reflect what we want to see in the pipeline
Check I captured everything 
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-471
=> feat: update serializer to match django export

django_app/redbox_app/settings.py, docker-compose.yml
=> chg: add additional SHA to CSP

django_app/redbox_app/redbox_core/views/misc_views.py
=> fix: missing import

django_app/redbox_app/redbox_core/views/misc_views.py
=> fix: authbroker-breaking-local

redbox-core/redbox/loader/loaders.py
=> disable metadata

redbox-core/redbox/models/settings.py
=> fix: correct pydantic usage of metadata var

redbox-core/redbox/models/settings.py
=> add bracket

README.md, django_app/redbox_app/setting_enums.py, django_app/redbox_app/templates/base.html
i.ai envs wasnt reflective of what we use at DBT
switching 'preprod' to UAT as that's our equivalent
=> feat: add uat

django_app/redbox_app/templates/macros/chat-macros.html
For better user experience it would be good if sources opened in new window
Adding blank attr so sources open in new window
=> feat: open sources in new window

redbox-core/tests/test_ingest.py
=> switch ingest to opensearch

django_app/redbox_app/redbox_core/views/__init__.py, django_app/redbox_app/redbox_core/views/api_views.py, django_app/redbox_app/urls.py, django_app/tests/views/test_api_views.py
The existing users endpoint, used by data-flow in order to ingest the data into Data Workspace, can be extremely slow in production, to the point that it now always hits the CloudFront timeout at 30 seconds. The endpoint is paginated, and it does get a few pages in, but because a each User entry includes all of their chats, which also includes all of their chat messages, it suspect that this causes the endpoint to be too slow when it hits a user with a lot of chats/messages.
In more detail, it's suspected that the slowness comes from 2 things:
1. The number database queries made to construct the data (no prefect_related or select_releated or similar is used)
2. And the amount of data - and so transfer time from the database and time it takes to convert it all to JSON
This add a new …
=> feat: new messages API endpoint

.github/workflows/branch-status-check.yml, .github/workflows/python-app.yml, redbox-core/redbox/app.py, redbox-core/redbox/graph/nodes/tools.py, redbox-core/redbox/graph/root.py
At the moment we are working on fixing our unit tests. Before we didn't enforce branch naming conventions but essentially our unit tests only run if we meet certain branch naming conventions and we're not checking for that.
Check if branches on opening a PR or on pushing to the repo have met certain criteria which matches that of our tests'. 
Are you happy with my approach?
=> chore: branch naming convention

django_app/redbox_app/redbox_core/serializers.py
We would like user email to be visible in our Redbox user details table on Data Workspace
Adds user email to the user API so we can access via our pipeline
Have I mistyped
=> feat: add email to user api

redbox-core/redbox/models/prompts.py
=> Fix prompts typo

django_app/redbox_app/redbox_core/admin.py
Ordering chat messages by date
Easier to filter and visualise route where invoked by ai vs user
=> feat: ordering chat messages by date

django_app/Dockerfile, django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/send-message.js, django_app/poetry.lock, django_app/pyproject.toml, django_app/redbox_app/redbox_core/views/__init__.py, django_app/redbox_app/redbox_core/views/chat_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/chats.html, django_app/redbox_app/urls.py, poetry.lock, pyproject.toml
We want the user to have the ability to record themselves in order to interact with the LLM
Implements the functionality required in order for the user to use a microphone if so wanted
Probably a good idea to run it locally and check all is well and it can understand you
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558/backlog?selectedIssue=REDBOX-670
=> feature: microphone implementation

.pre-commit-config.yaml
To automate linting , if make format is ran it will reformat everything.
=> Automating Linting

redbox-core/redbox/retriever/queries.py
=> set OpenSearch min score RAG to 6

django_app/Dockerfile
Reverting a change which caused this error when building the Docker container 
`Error: The current project could not be installed: No file/folder found for package redbox-app`
Fixes this bug.
=> Repin poetry

redbox-core/redbox/graph/root.py
Incorrect PromptSet import in root.py
=> Fixing import error

redbox-core/redbox/graph/nodes/processes.py
Add explicit tag to show that the information are from which worker agent.
=> Add information to indicate worker agent result

django_app/redbox_app/setting_enums.py
The UAT environment has been created but it is at a different than specified in `setting_enums.py` .
Updates the UAT URL.
=> Update UAT URL

django_app/Dockerfile, django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/send-message.js, django_app/poetry.lock, django_app/pyproject.toml, django_app/redbox_app/redbox_core/views/__init__.py, django_app/redbox_app/redbox_core/views/chat_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/chats.html, django_app/redbox_app/urls.py, poetry.lock, pyproject.toml
=> revert: microphone implementation

django_app/Dockerfile, django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/send-message.js, django_app/poetry.lock, django_app/pyproject.toml, django_app/redbox_app/redbox_core/views/__init__.py, django_app/redbox_app/redbox_core/views/chat_views.py, django_app/redbox_app/settings.py, django_app/redbox_app/templates/chats.html, django_app/redbox_app/urls.py, poetry.lock, pyproject.toml
This reverts commit 1d5b981f37d90b6a33226feb0f2c2c28de662859.
=> Revert "feature: microphone implementation (#146)"

django_app/frontend/src/js/web-components/chats/chat-history-item.js
Delete button does not work
Makes the delete button work
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-759
=> fix: delete chat button

django_app/frontend/src/styles.scss
We removed the citation highlight accidentally during GDS transfer of frontend
Adding back in citation highlighting
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-758
=> fix: accidental reverting of citation highlight

django_app/redbox_app/templates/base.html
=> Switch to redbox@dbt

redbox-core/redbox/chains/components.py
Adding max tokens to llm init.
=> add max token to llm

redbox-core/redbox/models/prompts.py
Updating the prompt in newroute by giving examples of expected output.
Run your Redbox in local app, select a document with has author info or use Power Chapter and test if 
test 1: response contains citations
prompt = @newroute who wrote the document?
expected outcome: response returned with at least 1 citation
test 2: response contains no citations
prompt = @newroute what has been mentioned about Saisakul?
expected outcome: response returned with no citation
=> Udating prompt to ensure correct format with citations is returned

django_app/redbox_app/settings.py
We want to roll out to all of DBT, so we should improve our django q
Increase number of workers, decrease Q_RETRY default. Putting it as an optional setting, so we can easily change these values in future
=> feat: increase no. of workers

unstructured/Dockerfile
=> roll back unstructured version

unstructured/Dockerfile
=> change unstructured correct version

docker-compose.yml
=> use unstructured version 0.0.83

django_app/frontend/src/styles.scss
We cant see the logo because the path is wrong
Correct the path
=> fix: incorrect reference to logo

django_app/redbox_app/templates/chats.html
=> fix: revert restructure of chats

django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/feedback-buttons.js, django_app/frontend/src/styles.scss
We want the feedback buttons to be radio format and we dont want a free text field anymore
Removes free text field for additional details and it changes things to radio
Does it look ok to you
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-792
=> Feat: create feedback buttons in radio format

django_app/frontend/src/js/web-components/chats/chat-history.js, django_app/frontend/src/js/web-components/chats/document-selector.js, django_app/redbox_app/templates/chats.html
Reverts uktrade/redbox#269
because our PM isnt happy with it yet as a component
=> Revert "feat: scrollable menu"

django_app/frontend/src/chat-styles.scss, django_app/frontend/src/iai-overrides.scss, django_app/frontend/src/js/web-components/chats/canned-prompts.js, django_app/redbox_app/templates/chats.html
This is a change to frontend where important icon in text box is being changed to a warning icon to display the message.
A change to frontend visualisation.
=> Updating warning

django_app/frontend/package.json
see https://github.com/i-dot-ai/redbox/pull/1456/files
=> Lock to a specific version of gov.uk design system

redbox-core/redbox/chains/runnables.py
When there is `ValidationException` issue due to malformed input sending to LLM. We need to be able to log what is sending to LLM so we can fix the issue. 
- add info on LLM input to log
=> Add log for llm input

django_app/redbox_app/settings.py
We are getting logs we dont want when a user uploads to S3. This is a PR to filter out those logs.
Putting a filter on the logs to prevent the unnecessary logs
=> feat: filter out s3 urls

redbox-core/redbox/chains/parser.py, redbox-core/redbox/chains/runnables.py, redbox-core/tests/graph/test_patterns.py
LLM returns None as value causing `ValidationError`. An equivalent of None in Json is null.
- In parser if we detect JSON decoding error, then change from None to null
- Modify test case to contain invalid JSON (containing None)
=> Fix None in Json

redbox-core/redbox/graph/edges.py
=> use space instead of regex

redbox-core/redbox/chains/runnables.py
Removing log as no logger needed.
=> remove debug llm log

django_app/frontend/src/js/web-components/chats/chat-message.js
Changing error message to be hidden in chat to only appear in message.
A more distinct error message following GDS styling
=> Changing error message to be hidden

django_app/redbox_app/redbox_core/middleware.py
=> fix: prevent dev error

.pre-commit-config.yaml, notebooks/Parlex_MCP_basic.ipynb
Adding MCP client call via streamable http
have mcp server spin up before running the notebook
=> add streamable http

django_app/redbox_app/settings.py
Changes required to use asim formatting for logs to allow log correlation in DataDog. 
Changes required to use asim formatting for logs to allow log correlation in DataDog. 
No
=> feat: use asim formatting for logging

redbox-core/redbox/graph/nodes/sends.py
adding timeout and max worker for the parallel tool calls.
=> add time out

django_app/redbox_app/templates/documents.html
The LLM on display on the Documents page is out of date. This PR fixes it.
Confirm that the model displayed is Claude 3.7 Sonnet.
=> Update LLM to Claude 3.7

redbox-core/redbox/graph/nodes/processes.py
This deletes the database file from memory once the question response is generated and resets the state to None. This avoids multiple .db files persisting.
Confirm that tabular QA works as normal and the created db file will be deleted once the answer is returned.
=> Remove the database file once question is asked

redbox-core/redbox/graph/nodes/tools.py, redbox-core/tests/test_tools.py
Add site argument to web search tool so that it can search on specific website/domain
https://uktrade.atlassian.net/browse/REDBOX-1060?atlOrigin=eyJpIjoiODY4MTk5ZjgwOWQ3NGNkOTg5Y2FlN2JmYWVjMmRhZDAiLCJwIjoiaiJ9
- update web search tool to have optional site argument
- add test for web search tool
=> Update web search tool for specific site

.github/PULL_REQUEST_TEMPLATE.md
We want to have a more thorough testing strategy
Adding additional check to PR template for people to think about adding a test
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-1069
=> feat: add test check to PR template

redbox/redbox/graph/root.py
=> remove chat agent

.github/PULL_REQUEST_TEMPLATE.md, redbox/redbox/loader/loaders.py, redbox/tests/test_chains.py, redbox/tests/test_ingest.py
=> feat: >80% test coverage

redbox/redbox/graph/nodes/tools.py, redbox/tests/test_tools.py
Make web search agent to return 20 search results (currently 5)
- web search agent to return 20 search results
- fix web search tool code to only return search results
=> change websearch to return 20 results

django_app/redbox_app/redbox_core/consumers.py
UWotm8 error generated from no await.
=> text conversion await

django_app/oritem8.txt, django_app/redbox_app/redbox_core/consumers.py, django_app/redbox_app/redbox_core/services/message.py, django_app/tests/test_consumers.py
Add a test to check functionality of uwotm8 American to British conversion. 
Please test conversion works for text and citations.
=> add uwotm8 test
