django_app/redbox_app/redbox_core/middleware.py, django_app/redbox_app/redbox_core/serializers.py, django_app/redbox_app/redbox_core/views/api_views.py, django_app/redbox_app/settings.py
We would like to build a pipeline in data workspace that outputs all our redbox user data into a dataset. This is the json output that will hopefully allow us to move forward and build our pipeline.
changing pre existing API to fetch all user data and setting up appropriate security middleware to prevent exposing user data without relevant authentication header
Check you're happy this is safe enough for our purposes.
=> feat: api middleware integration and fetch all user history

django_app/redbox_app/settings.py
Update CSP to use suggested links from google https://developers.google.com/tag-platform/security/guides/csp#google_analytics_4_google_analytics
=> update CSP to use new GA links

django_app/redbox_app/templates/base.html
In order to get more detailed granular tracking, we need to use google tag manager
=> chg: replace basic google analytics with google tag manager

redbox-core/redbox/chains/parser.py, redbox-core/redbox/loader/loaders.py
Meta data extraction use a function called `with_structured_output` to force LLM to return into specified output. However, Claude doesn't follow this instructions therefore causing error.
- Create a `Claudeparser` class to deal with Claude output
- Update the metadata extraction to use `Claudeparser`
=> using claude parser for metadata

django_app/redbox_app/settings.py
Following conversation with Vishal he spotted that we are getting some additional errors causing GTM to not work correctly
So following that and looking at this https://developers.google.com/tag-platform/security/guides/csp I've added in all the suggested urls etc, (think the general approach will need a review) also added the stuff for GTM preview, should allow easier debugging etc
=> chg: update CSP to work with GTM

django_app/tests/conftest.py, django_app/tests/views/test_api_views.py
There are some broken tests from some legacy work. This fixes just some of them: the ones in test_api_views.py
There were 5 issues causing the tests to fail that this change fixes:
- An incorrect assumption on the form of an error message in the case of a 403
- Using a now-removed date_joined field
- Passing an email address into model creation, where is also determined the email address based on username.
- Assuming that a regular user can access the view-message endpoint, when they
(correctly) cannot, and instead need to pass an API key
- Incorrect assumption on the structure of the response to user-view
Looking at the code and making sure more tests don't fail should be enough.
N/A
=> test: fix API tests

redbox-core/redbox/graph/root.py, redbox-core/redbox/models/prompts.py
- fixed the summarisation prompt to prevent LLM getting confused as it summarise entire document and not just the last section of the document
- fixed ThrottlingException limit issues for summarisation using exponential backoff (implemented in the 3 summarisation nodes).
=> Fix summarisation and exponential backoff for summarisation

django_app/redbox_app/redbox_core/migrations/0076_citation_text_in_answer.py
** This PR does cause test-django to fail but this change will be rolled back after it has been applied to dev. **
Prod says
Dev says
So we need to apply to dev but not to prod in order to allow any future migrations to apply. Essentially "tricking" dev.
Switch 76 to alter not add
=> fix: text_in_answer already exists and prevents further migrations

redbox-core/tests/graph/test_app.py, redbox-core/tests/test_ingest.py
Final PR to fix the broken unit tests from migrating from opensearch/diverging so far from i.AI work. After this, we can mandate all tests passing before merging to dev and also from now on follow a proper TDD process for new features.
Making a variety of changes to the mocking to ensure the tests pass.
Do you agree? Do you think we are being too lenient on the parameters of the test? Do the tests pass for you?
=> chore: fix redbox tests

redbox-core/redbox/graph/nodes/processes.py
We are getting numerous flags from sentry about:
`EventStreamError: An error occurred (serviceUnavailableException) when calling the InvokeModelWithResponseStream `
We dont want this anymore. Its probably because too many requests are being sent to bedrock, so exponential backoff is a healthy way to try mitigate this error.
Implement exponential backoff. Maybe further in future we should look at other errors to catch (ThrottlingException etc.)
Check it is a suitable implementation
=> fix: implement exponential backoff to resolve EventStreamError

django_app/redbox_app/redbox_core/serializers.py, django_app/redbox_app/urls.py, django_app/tests/conftest.py, django_app/tests/test_admin.py, django_app/tests/views/test_api_views.py
Following on from DIAPPs work ([here](https://github.com/uktrade/redbox/pull/76)) we would like to ensure the errors stop for our other two tables too. DIAPP has now covered the information we need regarding Chat/ChatMessages so I'm severing the connection between chats in the UserSerializer
Remove ChatSerializer as its covered by ChatMessageSerializer
Add extra fields to UserSerializer
Remove chats from being called unnecessarily in the UserSerializer which is causing the 504 timeouts
Update relevant tests
=> fix: prevent 504 for user table

django_app/redbox_app/redbox_core/models.py, django_app/redbox_app/redbox_core/views/document_views.py
Currently, documents which have errored cannot be deleted. Or at least, they are "technically" deleted but because they are already removed from opensearch users are seeing a random error, when they are automatically deleted.
Just redirect the user so they don't see a random false flag regarding inactive file uploads. Its not important to them as if a doc fails to upload, it will automatically delete.
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-500
=> feat: redirect user trying to delete failed document upload

redbox-core/redbox/graph/nodes/processes.py, redbox-core/redbox/graph/root.py
To avoid a variety of constant timeouts we get flagged in Sentry that users must be experiencing, implement the rest of exponential backoff concept with consistent approach for the nodes.
Adding langgraph's RetryPolicy and removing standardised Python approach to ensure we have matching applications of exponential backoff throughout.
Have I missed anything? More or less verbose retry policy?
https://github.com/uktrade/redbox/pull/80/files
=> fix: implement exponential backoff for 504 nodes

redbox-core/redbox/retriever/queries.py
We do not have 'embedding' properties in our vector store, instead we use `vector_field`
- changing `* embedding` to `vector_field`
- check that retriever tests pass
- check the application running as usual in docker
=> change *embeding to vectore_field in openseaerch query

notebooks/LLM_choose_route.ipynb, redbox-core/redbox/chains/components.py, redbox-core/redbox/retriever/__init__.py, redbox-core/redbox/retriever/queries.py, redbox-core/redbox/retriever/retrievers.py
Can the supervisor agent correctly classify the user intent and reliably call the correct tool?
As a user I want to be able to get the response from a correct tool without having to use specific keywords.
- spike to investigate optimal prompts that allow LLM to determine best route give user's question
- add`BasicMetadataRetriever` to retrieve basic metadata: name, keywords, description
- add `get_minimum_metadata` to query open search and return metadata
- add `get_basic_metadata_retriever` function to get `BasicMetadataRetriever`
- inspect the notebook and test if you can run it.
- suggestion on additional explanation or wording for the notebook context.
=> Spike LLM to choose route

.env.example, redbox-core/redbox/models/chain.py
Currently we hard coded whether self_route is on or off.
Need Nan easy way to change setting.
- use env var to control self_route
=> turn self route using env

django_app/Dockerfile, django_app/redbox_app/redbox_core/views/document_views.py
At the moment, if a user uploads a document that contains text unstructured cannot interpret (not utf-8 format), then the user document upload will fail, they’ll flag it to us, we’ll investigate and provide them with a fixed doc. This should just be integrated in the codebase to remove the necessity of manually fixing it.
Also, we say we can process .doc files, we can't. We need some logic to convert it to docx which is accepted by the unstructured io.
Amending the upload view to assess the document pre processing for its compatibility with unstructured and converting it if required.
Do you agree with the approach? Any improvements to be made?
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-609 …
=> feat: Intercept incompatible (not UTF-8) text on upload and handle .doc

redbox-core/redbox/graph/root.py
We are getting timeouts related to a large variety of our nodes. It would simply be better if all of them had a retry policy in the circumstance in which the invoking causes some form of error
Adding exponential backoff to all nodes
=> fix: adding retry policy to all nodes to prevent timeouts

django_app/redbox_app/redbox_core/views/document_views.py
Some errors on deployment to prod that isn't reflected in dev - probably because utf-8 conversion is running against all docs instead of particular file types.
Ensure it doesn't run against primarily PDFs but also other files. This can be changed in future dependent on user errors raised on sentry.
You ok with the approach?
=> fix: prevent files not requiring utf8 check from conversion

redbox-core/redbox/graph/edges.py, redbox-core/redbox/graph/root.py, redbox-core/tests/graph/test_app.py
In the current Redbox search graph logic, if self_route is enabled and @search is used, it still possible to go to summarise if RAG cannot answer question. This is not followed the expected behaviour.
We need to add a node in search graph to check if keyword was used so that it forces to only use RAG even if RAG cannot find answer.
- add a new node to check if @search keyword was used.
- check that when @search is used, only search route was used to produce final result
- example question: what are accelerometers in power chapter.
=> add check if summarise keyword was used node

django_app/redbox_app/redbox_core/consumers.py, django_app/redbox_app/redbox_core/views/document_views.py
We are getting a variety of sentry errors in relation to different parts of the ode
Fixing errors specifically in regards to ai_settings_id not existing for an LLM invoke and file_name is the incorrect field name, it should be name
To get rid of some of the errors we get in the sentry
=> fix: sentry error for ai_settings_id and for S3file

django_app/redbox_app/redbox_core/views/document_views.py
S3File does not have a field_name, it has a name.
Stop errors on doc/docx uploads
=> fix: uploaded file should point to name not field_name

redbox-core/redbox/graph/nodes/processes.py, redbox-core/redbox/graph/root.py
External Data Agent prompt were not passed when creating this agent.
The `create_agent` function needs to be able to receive different agent system prompts, so that this function can be reused.
=> Create agent to receive prompts

redbox-core/redbox/api/format.py, redbox-core/redbox/chains/runnables.py, redbox-core/redbox/graph/root.py, redbox-core/redbox/models/chain.py, redbox-core/redbox/models/prompts.py, redbox-core/tests/graph/test_app.py
Inline citations help user understand where from the source the LLM derives answer from, and also create trusts.
Show inline citations when using self_route and @search.
- [ x] No
Test in docker to see the response return with citations.
=> Add citation to search

django_app/redbox_app/redbox_core/views/misc_views.py, django_app/tests/views/test_misc_views.py
As a user
When I first log into Redbox
Then I want to see the main home page
So that I can be introduced to the service
As a user
From my second log in forward
When I log into Redbox
Then I should be redirected to the ‘Chats’ page
So that I can started using the service straight away
Not logged in users will see homepage, logged in users will go to chat page.
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?assignee=5e66610684dcfc0cf39102d4&selectedIssue=REDBOX-760
=> feat: redirect logged in users to chat page

django_app/frontend/src/styles.scss, django_app/redbox_app/templates/accessibility-statement.html, django_app/redbox_app/templates/base.html, django_app/redbox_app/templates/privacy-notice.html, django_app/redbox_app/templates/support.html, django_app/redbox_app/urls.py, tests/pages.py
The footer of Redbox needs to match the new GDS styling of the app.
- Replaces the I.AI footer with a GDS footer.
- Improves the formatting of the ancillary pages - wrapping them in proper `<main>` and gov-uk `<div>` tags
*The size of this PR is misleading as most 'changed' lines have just been indented a bit more
=> Make footer GDS styled

redbox-core/redbox/models/prompts.py
The evaluator is currently doing:
1) answer user question 
2) provide citation
3) evaluate whether answer satisfies user question/intention
which is too complex for a single agent. 
Change the evaluator prompt so that it only answers questions with citations
1. Run Redbox app in docker
2. Test using @newroute your question
3. Redbox should return response without error.
=> remove evaluation part from evaluator

django_app/redbox_app/settings.py, django_app/redbox_app/storage.py
At the moment our S3Uploader is sending chunks to the main bucket and not deleting them, instead of just to the user's folder
This extends the parent S3FileUploadHandler and creates a custom one, which ensures the document is only uploaded once, to the user's folder.
Not locally as S3 is not used but I have tested this in UAT and dev with many documents and it successfully reduces upload time.
=> fix: prevent redundant file upload to main s3 bucket

redbox-core/redbox/models/prompts.py
- when user ask for summarisation, sometimes the planner ask document agent to summarise, in addition asking summarisation agent to generate another summary. This leads to duplicate summaries.
Changes in prompt aim to prevent this issue
How to test:
- run docker compose
- from UI, select a document and test summarisation via newroute: for example @newroute summarise this document
=> improve planner prompt

django_app/redbox_app/redbox_core/consumers.py, django_app/tests/test_consumers.py, redbox-core/redbox/graph/root.py
Correct graph is not invoked when using @route e.g. @search, @gadget, etc. If use @route it goes to chat if no document is selected, otherwise self-route graph is invoked.
Example: prompt: @gadget how do I renew passport?
Expected results: Response generated using @gadget route
Results: Response generated using @chat
See https://uktrade.atlassian.net/browse/REDBOX-844?atlOrigin=eyJpIjoiZjk1NTkxNjA4OTliNDNlZmIyZDg5Zjc0NzBhMWY0ZjIiLCJwIjoiaiJ9
- use -2 as index.
- fix consumers.py test. 
- add a node to remove keyword in newroute
Tests
1. Don't select a document, use @newroute how to renew passport. Follow up question: @newroute how much is it?
2. Don't select a document, use @search how to renew passport. Check the response is from @search route
=> Fix @route keyword not detect

django_app/redbox_app/templates/chats.html
=> fix: revert restructure of chats (#260)

django_app/frontend/src/chat-styles.scss
When a user presses send, there is an outline around the box. We dont want this outline
CSS to get rid of the outline when a user sends a message without touching any JS which would impact the streaming functionality
Can you see the outline after you recompile the CSS and send a message?
https://uktrade.atlassian.net/jira/software/projects/REDBOX/boards/558?selectedIssue=REDBOX-856
=> fix: prevent outline on message send

.copilot/phases/pre_build.sh
Bugfix including trailing "|" in pre-build script.
=> Fixing issue in pre-build script

django_app/redbox_app/templates/macros/chat-macros.html
We want sources to appear only once in the sources section of a chat. 
We are adding a check that returns the name in the html if it hasn't already been displayed.
Confirm that new and previous chats that returned citations with one or more files included only list each file once with citation links being unaffected.
**Before**
**After**
=> Adding back display uniqueness check

django_app/redbox_app/templates/macros/chat-macros.html
We want source files to link to the response info page and not to directly download the file
Switching the href attribute to refer to the response info page.
Confirm that for previous and new chats, when a citations link is provided, it goes to the response info page
After clicking the link, the behaviour should be below
**Before**
**After**
=> Switching link to refer to citations page

django_app/redbox_app/jinja2.py, django_app/redbox_app/templates/citation_fragment.html
Redbox now directly writes the citation id directly into the text response. This means that when responses are copied, the text will include ref_1, ref_2
Uses a filter to scrub the text of ref_x references
=> feat: remove refs from citation text

redbox-core/redbox/chains/runnables.py
There should be a role for each message in chat prompt template.
=> add role to prompt template

.envrc.example, .gitignore, aws-login.sh
… if available to avoid potential profile conflicts
Currently, logging into AWS uses the "default" profile, this change allows it to pull variables from an .envrc file using direnv for cleaner service/profile naming to avoid conflicts. This will also help with future dbt-platform-helper implementations.
- Updated script to pull from .envrc if it exists and run `direnv allow` to export to the current environment
- Added functionality to copy credentials to notebooks and django_app directories to avoid having to use a single venv for all apps within the project.
run `./aws-login` from the project root and ensure the .aws directories and credentials are created within the django_app/notebooks directories (assuming the root .aws/credentials.example directory and file already exists).
=> Chore: Updated AWS login script

django_app/frontend/src/chat-styles.scss, django_app/frontend/src/js/web-components/chats/chat-history.js, django_app/frontend/src/js/web-components/chats/document-selector.js, django_app/frontend/src/js/web-components/show-more.js, django_app/frontend/src/styles.scss
- Fixed side panel scrolling overflow
- Fixed footer logo height/padding
- Fixed <main> div min-height by overriding I.AI design system styling to prevent excessive space on page
- Enhanced show-more component logic to save/restore previous element display value
- Updated depreciated import statement for govuk-frontend
- 
Note: If using a separate development Macbook/laptop - within the same network - set ADDITIONAL_HOSTS in your .env to the ip address of your DBT device for testing. The server can be accessed from your DBT laptop with <DEV_LAPTOP_IP>:8080
- Check that the scroll bar does not flow into the footer on DBT laptop. 
- The footer logo should also have a reduced padding between it and the copyright link
=> bugfix: Persistent side panel

django_app/redbox_app/redbox_core/views/api_views.py
We have an iteration for attempting to connect to creds, this doesnt need to be there anymore - custom terraform mitigates this issue and it doesnt apply to redbox
Removes legacy attempt to connect to transcribe service. We are covered for this.
=> fix: redundant iteration

redbox-core/redbox/chains/runnables.py, redbox-core/redbox/models/chain.py, redbox-core/redbox/models/prompts.py
Backticks should only be used for inline coding, variable names, technical syntax, but not English text
https://uktrade.atlassian.net/browse/REDBOX-931?atlOrigin=eyJpIjoiOWM1ZTI3Njk3YmUyNDU1MThhMmQxYmQ2MWQ2OGRjZTMiLCJwIjoiaiJ9
- added answer system prompt
=> prompt not to use backticks

django_app/redbox_app/redbox_core/models.py
We are getting an error when users access a chat in which the document has been deleted previously, there is no longer an associated url
First check the file still exists, then create the URL
https://sentry.ci.uktrade.digital/organizations/dit/issues/160898/?project=272&referrer=slack
=> fix: prevent nonetype url error

django_app/poetry.lock, django_app/pyproject.toml, poetry.lock, pyproject.toml
I've had to update the ddtrace package to 3.10.0 due to an issue with ddtrace and how Django handles concurrency.
Fixing the issues with ddtrace that prevent some asycronous event loops from happening properly in Django. 
Test locally and ensure you don't see this error: 
`object HttpResponse can't be used in 'await' expression`
https://github.com/DataDog/dd-trace-py/issues/10754
https://django.readthedocs.io/en/stable/topics/async.html#async-safety
=> fix: ddtrace async issues 

Makefile, aws-login.sh, dev.sh, django_app/frontend/src/js/web-components/chats/canned-prompts.js, django_app/frontend/src/js/web-components/chats/chat-message.js, django_app/frontend/src/js/web-components/chats/message-input.js, django_app/frontend/src/stylesheets/chat-styles.scss, django_app/frontend/src/stylesheets/components/_index.scss, django_app/frontend/src/stylesheets/components/chat-message.scss, django_app/frontend/src/stylesheets/components/chat-title.scss, django_app/frontend/src/stylesheets/components/show-more.js, django_app/frontend/src/stylesheets/components/show-more.scss, django_app/frontend/src/stylesheets/components/side-panel.scss, django_app/frontend/src/stylesheets/govuk-custom/_index.scss, django_app/frontend/src/stylesheets/govuk-custom/govuk-textarea.scss, django_app/frontend/src/stylesheets/iai-overrides.scss, django_app/frontend/src/stylesheets/icons/delete.scss, django_app/frontend/src/stylesheets/icons/edit.scss, django_app/frontend/src/variables.scss, django_app/frontend/tests-web-components/canned-prompts.spec.js, django_app/frontend/tests-web-components/copy-text.spec.js, django_app/frontend/tests-web-components/message-input.spec.js, django_app/frontend/tests-web-components/utils.js, django_app/redbox_app/templates/chats.html, django_app/redbox_app/templates/macros/chat-history-macros.html, docs/installation/running-django-locally.md
This PR fixes the edit chat title button showing when no chat is selected bug and some minor style discrepancies.
I also updated the getting started guide and added a few make commands to make setting up a bit easier. 
Lastly I moved the chat-title and chat-message styles out of chat-styles.scss into their own component stylesheets.
- Fixed styling for side-panel underline and hover states (underline thickness and hover color)
- Put icon hover states behind optional class
- Added make commands for setting up local environment variables
- Updated AWS login script to not be dependant on direnv, the file will now be sourced directly regardless if its installed. Also created a Makefile command
- Updated documentation to reflect changes to makefile
- Changed chat textarea to be font-size: 16px …
=> chore: Fixed styling for underline, hover and edit chat button.

django_app/frontend/src/redbox_design_system/rbds/iai-overrides.scss
This PR is to fix the spacing gap at the top of the page caused by unnecessary padding at the top of the main div.
Remove padding from `.govuk-main-wrapper`
- Ensure spacing is gone from the top of the sidepanel/main div
Before:
After:
[REDBOX-976](https://uktrade.atlassian.net/browse/REDBOX-976)
[REDBOX-976]: https://uktrade.atlassian.net/browse/REDBOX-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Fix spacing gap at top of left panel

redbox-core/redbox/graph/root.py
Bug -> legislation route currently build newroute graph where legislation tool is not available
Correctly call the legislation graph where the applicable tool is available
-
Build locally, use prompts prefixed with https://github.com/legislation to check that answers relate to the question asked, and citations only point to http://legislation.gov.uk/ and are valid urls
=> correctly call legislation graph
